import { execa } from "execa";
import { writeFileSync } from "fs";
import { resolve } from "path";
import chalk from "chalk";

export class TerraformError extends Error {
  constructor(
    public command: string,
    public exitCode: number
  ) {
    super(`Terraform ${command} failed with exit code ${exitCode}`);
    this.name = "TerraformError";
  }
}

interface TerraformOptions {
  cwd: string;
  variables?: Record<string, unknown>;
  backendConfig?: Record<string, string>;
  awsProfile?: string;
}

/**
 * Run a terraform command with streaming output
 */
async function runTerraform(args: string[], options: TerraformOptions): Promise<string> {
  const { cwd, variables, backendConfig, awsProfile } = options;

  const fullArgs = [...args];

  if (backendConfig) {
    for (const [key, value] of Object.entries(backendConfig)) {
      fullArgs.push(`-backend-config=${key}=${value}`);
    }
  }

  if (variables) {
    for (const [key, value] of Object.entries(variables)) {
      const strValue =
        typeof value === "object" ? JSON.stringify(value) : String(value);
      fullArgs.push(`-var=${key}=${strValue}`);
    }
  }

  // Set up environment variables, including AWS profile if provided
  const env = { ...process.env };
  if (awsProfile) {
    env.AWS_PROFILE = awsProfile;
  }

  try {
    const result = await execa("terraform", fullArgs, {
      cwd,
      stdio: args.includes("-json") ? "pipe" : "inherit",
      env,
    });
    return result.stdout;
  } catch (error) {
    const exitCode = (error as { exitCode?: number }).exitCode ?? 1;
    throw new TerraformError(args[0], exitCode);
  }
}

/**
 * Initialize a Terraform module
 */
export async function init(
  modulePath: string,
  options: { reconfigure?: boolean; backendConfig?: Record<string, string>; awsProfile?: string } = {}
): Promise<void> {
  console.log(chalk.blue(`Initializing Terraform in ${modulePath}...`));

  const args = ["init"];
  if (options.reconfigure) {
    args.push("-reconfigure");
  }

  await runTerraform(args, {
    cwd: modulePath,
    backendConfig: options.backendConfig,
    awsProfile: options.awsProfile,
  });

  console.log(chalk.green("Terraform initialized successfully."));
}

/**
 * Run terraform plan
 */
export async function plan(
  modulePath: string,
  variables?: Record<string, unknown>,
  awsProfile?: string
): Promise<void> {
  console.log(chalk.blue(`Planning Terraform changes in ${modulePath}...`));
  await runTerraform(["plan"], { cwd: modulePath, variables, awsProfile });
}

/**
 * Run terraform apply
 */
export async function apply(
  modulePath: string,
  variables?: Record<string, unknown>,
  autoApprove = false,
  awsProfile?: string
): Promise<void> {
  console.log(chalk.blue(`Applying Terraform changes in ${modulePath}...`));

  const args = ["apply"];
  if (autoApprove) {
    args.push("-auto-approve");
  }

  await runTerraform(args, { cwd: modulePath, variables, awsProfile });
  console.log(chalk.green("Terraform apply completed successfully."));
}

/**
 * Run terraform destroy
 */
export async function destroy(
  modulePath: string,
  variables?: Record<string, unknown>,
  autoApprove = false,
  awsProfile?: string
): Promise<void> {
  console.log(chalk.yellow(`Destroying Terraform resources in ${modulePath}...`));

  const args = ["destroy"];
  if (autoApprove) {
    args.push("-auto-approve");
  }

  await runTerraform(args, { cwd: modulePath, variables, awsProfile });
  console.log(chalk.green("Terraform destroy completed successfully."));
}

/**
 * Get Terraform outputs as JSON
 */
export async function output(
  modulePath: string,
  awsProfile?: string
): Promise<Record<string, { value: unknown }>> {
  const result = await runTerraform(["output", "-json"], { cwd: modulePath, awsProfile });
  return JSON.parse(result);
}

/**
 * Write a backend.tf file for S3 remote state
 */
export function writeBackendConfig(
  modulePath: string,
  config: {
    bucket: string;
    key: string;
    region: string;
    dynamodb_table: string;
  }
): void {
  const content = `# Auto-generated by lab CLI - do not edit manually
terraform {
  backend "s3" {
    bucket         = "${config.bucket}"
    key            = "${config.key}"
    region         = "${config.region}"
    dynamodb_table = "${config.dynamodb_table}"
    encrypt        = true
  }
}
`;

  const backendFile = resolve(modulePath, "backend.tf");
  writeFileSync(backendFile, content);
  console.log(chalk.green(`Generated backend configuration: ${backendFile}`));
}
